AllCops:
  Exclude:
    - spec/okjson.rb
Lint/Void:
  Exclude:
    - spec/cookies_spec.rb
Style/StructInheritance:
  Exclude:
    - lib/sinatra/reloader.rb
Style/CaseEquality:
  Exclude:
    - lib/sinatra/multi_route.rb
    - lib/sinatra/config_file.rb
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
