---
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx
  - jruby
  - jruby-head
  - ruby-head
matrix:
  include:
    - { rvm: 1.8.7, env: tilt=master    }
    - { rvm: 1.9.3, env: tilt=master    }
    - { rvm: 2.2, env: rack=master    }
    - { rvm: 2.2, env: sinatra=master }
  allow_failures:
    - env: tilt=master
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
    - env: sinatra=master
before_install:
  - gem update bundler
notifications:
  recipients:
    - _@trevorbramble.com
    - e@zzak.io
notifications:
  slack: sinatrarb:LQGhUfGYcqRgRzwKea0bqUhY
